# Generated by Django 5.0.7

import uuid
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(help_text='Field identifier from checklist', max_length=50)),
                ('s3_key', models.CharField(help_text='S3 object key', max_length=500)),
                ('s3_url', models.URLField(help_text='Public URL of the uploaded photo', max_length=1000)),
                ('captured_at', models.DateTimeField(help_text='When the photo was captured')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude where photo was captured', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude where photo was captured', max_digits=9, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded to server')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_uploads', to='jobs.job')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(help_text='Field identifier from checklist', max_length=50)),
                ('s3_key', models.CharField(help_text='S3 object key', max_length=500)),
                ('s3_url', models.URLField(help_text='Public URL of the uploaded signature', max_length=1000)),
                ('captured_at', models.DateTimeField(help_text='When the signature was captured')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the signature was uploaded to server')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_uploads', to='jobs.job')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photoupload',
            index=models.Index(fields=['job', 'field_id'], name='media_app_phot_field_id_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='photoupload',
            index=models.Index(fields=['uploaded_at'], name='media_app_phot_upload_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureupload',
            index=models.Index(fields=['job', 'field_id'], name='media_app_sig_field_id_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='signatureupload',
            index=models.Index(fields=['uploaded_at'], name='media_app_sig_upload_123456_idx'),
        ),
    ]
