# Generated by Django 6.0.3 on 2026-03-22 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('job_description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(help_text='Stores the dynamic form definition')),
                ('version', models.PositiveIntegerField(default=1)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_schema', to='jobs.job')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Maps field_id to value')),
                ('is_complete', models.BooleanField(default=False)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('client_modified_at', models.DateTimeField(blank=True, help_text='Sent by client, for conflict detection', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_response', to='jobs.job')),
            ],
            options={
                'ordering': ['-last_modified_at'],
            },
        ),
    ]
